services:
  configurator:
    build:
      context: .
      dockerfile: Dockerfile
    image: tencent-custom-jwt-poc:local
    command: ["/app/configurator/TencentOidcPoc.Configurator.dll"]
    env_file:
      - .env
    environment:
      STATE_DIRECTORY: /state
    volumes:
      - ./state:/state

  login-demo:
    depends_on:
      configurator:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: Dockerfile
    image: tencent-custom-jwt-poc:local
    command: ["/app/login-demo/TencentOidcPoc.LoginDemo.dll"]
    env_file:
      - .env
    environment:
      STATE_DIRECTORY: /state
      TENCENT_SECRET_ID: ""
      TENCENT_SECRET_KEY: ""
    volumes:
      - ./state:/state
